In [1]:
from tensorflow import keras
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet import preprocess_input, decode_predictions
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras import backend as K

import tensorflowjs as tfjs



from PIL import Image

import numpy as np
import tensorflow as tf

In [2]:
model = load_model('./saved/model_v1_final.h5')

W0809 11:22:38.041903 139826341795648 deprecation.py:323] From /media/HDD/DogeNetTFModel/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [3]:
tfjs.converters.save_keras_model(model, "./")

In [6]:
def prepare_image(file):
    img_path = ''
    img = image.load_img(img_path + file, target_size=(224, 224))
    img_array = np.array(img)
    img_array_expanded_dims = np.expand_dims(img_array, axis=0)
    return keras.applications.mobilenet.preprocess_input(img_array_expanded_dims)

In [7]:
test_image2 = "./testing/shtzu.jpg"
preprocessed_image = prepare_image(test_image2)
predictions = model.predict(preprocessed_image)
# results = decode_predictions(predictions)
# results
predictions
predictions.argmax(axis=-1)

array([4])

In [8]:
preprocessed_image = prepare_image(test_image)
predictions = model.predict(preprocessed_image)
# results = decode_predictions(predictions)
# results
predictions
predictions.argmax(axis=-1)

array([102])

In [9]:
test_image2 = "./testing/dog.jpg"
preprocessed_image = prepare_image(test_image2)
predictions = model.predict(preprocessed_image)
# results = decode_predictions(predictions)
# results
predictions
predictions.argmax(axis=-1)

array([8])

In [10]:
predictions.argmax(1)

array([8])

In [11]:
top_values, top_indices = K.get_session().run(tf.nn.top_k(predictions, k=5))

AttributeError: module 'tensorflow.python.keras.api._v2.keras.backend' has no attribute 'get_session'

In [12]:
top_values

NameError: name 'top_values' is not defined

In [13]:
top_indices

NameError: name 'top_indices' is not defined

In [2]:
train_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
train_generator = train_datagen.flow_from_directory('../data/Images',
                                                  target_size=(224,224),
                                                  color_mode='rgb',
                                                  batch_size=32,
                                                  class_mode='categorical',
                                                  shuffle=True)

Found 20888 images belonging to 121 classes.


In [3]:
import json

In [11]:
output_classes = json.dumps(train_generator.class_indices)

In [13]:
output_classes = json.loads(output_classes)
output_classes

{'Nothing': 0,
 'n02085620-Chihuahua': 1,
 'n02085782-Japanese_spaniel': 2,
 'n02085936-Maltese_dog': 3,
 'n02086079-Pekinese': 4,
 'n02086240-Shih-Tzu': 5,
 'n02086646-Blenheim_spaniel': 6,
 'n02086910-papillon': 7,
 'n02087046-toy_terrier': 8,
 'n02087394-Rhodesian_ridgeback': 9,
 'n02088094-Afghan_hound': 10,
 'n02088238-basset': 11,
 'n02088364-beagle': 12,
 'n02088466-bloodhound': 13,
 'n02088632-bluetick': 14,
 'n02089078-black-and-tan_coonhound': 15,
 'n02089867-Walker_hound': 16,
 'n02089973-English_foxhound': 17,
 'n02090379-redbone': 18,
 'n02090622-borzoi': 19,
 'n02090721-Irish_wolfhound': 20,
 'n02091032-Italian_greyhound': 21,
 'n02091134-whippet': 22,
 'n02091244-Ibizan_hound': 23,
 'n02091467-Norwegian_elkhound': 24,
 'n02091635-otterhound': 25,
 'n02091831-Saluki': 26,
 'n02092002-Scottish_deerhound': 27,
 'n02092339-Weimaraner': 28,
 'n02093256-Staffordshire_bullterrier': 29,
 'n02093428-American_Staffordshire_terrier': 30,
 'n02093647-Bedlington_terrier': 31,
 'n0209

In [14]:
for o in output_classes:
    print(o)

Nothing
n02085620-Chihuahua
n02085782-Japanese_spaniel
n02085936-Maltese_dog
n02086079-Pekinese
n02086240-Shih-Tzu
n02086646-Blenheim_spaniel
n02086910-papillon
n02087046-toy_terrier
n02087394-Rhodesian_ridgeback
n02088094-Afghan_hound
n02088238-basset
n02088364-beagle
n02088466-bloodhound
n02088632-bluetick
n02089078-black-and-tan_coonhound
n02089867-Walker_hound
n02089973-English_foxhound
n02090379-redbone
n02090622-borzoi
n02090721-Irish_wolfhound
n02091032-Italian_greyhound
n02091134-whippet
n02091244-Ibizan_hound
n02091467-Norwegian_elkhound
n02091635-otterhound
n02091831-Saluki
n02092002-Scottish_deerhound
n02092339-Weimaraner
n02093256-Staffordshire_bullterrier
n02093428-American_Staffordshire_terrier
n02093647-Bedlington_terrier
n02093754-Border_terrier
n02093859-Kerry_blue_terrier
n02093991-Irish_terrier
n02094114-Norfolk_terrier
n02094258-Norwich_terrier
n02094433-Yorkshire_terrier
n02095314-wire-haired_fox_terrier
n02095570-Lakeland_terrier
n02095889-Sealyham_terrier
n020960

In [19]:
with open('output_classes.json', 'w') as outfile:
    json.dump(train_generator.class_indices, outfile)

In [9]:
output_classes

'{"Nothing": 0, "n02085620-Chihuahua": 1, "n02085782-Japanese_spaniel": 2, "n02085936-Maltese_dog": 3, "n02086079-Pekinese": 4, "n02086240-Shih-Tzu": 5, "n02086646-Blenheim_spaniel": 6, "n02086910-papillon": 7, "n02087046-toy_terrier": 8, "n02087394-Rhodesian_ridgeback": 9, "n02088094-Afghan_hound": 10, "n02088238-basset": 11, "n02088364-beagle": 12, "n02088466-bloodhound": 13, "n02088632-bluetick": 14, "n02089078-black-and-tan_coonhound": 15, "n02089867-Walker_hound": 16, "n02089973-English_foxhound": 17, "n02090379-redbone": 18, "n02090622-borzoi": 19, "n02090721-Irish_wolfhound": 20, "n02091032-Italian_greyhound": 21, "n02091134-whippet": 22, "n02091244-Ibizan_hound": 23, "n02091467-Norwegian_elkhound": 24, "n02091635-otterhound": 25, "n02091831-Saluki": 26, "n02092002-Scottish_deerhound": 27, "n02092339-Weimaraner": 28, "n02093256-Staffordshire_bullterrier": 29, "n02093428-American_Staffordshire_terrier": 30, "n02093647-Bedlington_terrier": 31, "n02093754-Border_terrier": 32, "n020